### ISSUE TITLE
[+] Support Android & Windows

### ISSUE THREAD

**Issue by Azathothas** [xplshn/bigdl#69]
The bins in https://bin.ajam.dev/arm64_v8a_Android/ & https://bin.ajam.dev/x64_Windows/ are out of alpha/WIP phase and now can be considered beta (many more are yet to be added),
Would be nice to add support for :
- Android (You can either rely on termux (will make things quite easy) or be pure adb shell only (a bit tricky due to perms))
- Windows (this maybe tricky, as windows defender might get in the way)
And, the url struct follow same `uname -m` equivalent as well: https://github.com/Azathothas/Toolpacks?tab=readme-ov-file#cli
```bash
Android --> getprop ro.product.cpu.abi --> arm64-v8a || arm64-v8a-Android || arm64_v8a_Android
Windows --> $env:PROCESSOR_ARCHITECTURE --> AMD64 || AMD64_Windows_NT || x64_Windows

```

**Comment by xplshn** [comment]
I will try, but I've got no experience with Windows apart from Windows XP x64. My machines cannot run newer Window versions (its not unbearably slow, its completely unusable)

**Comment by Azathothas** [comment]
Github Actions RDP (via Tailscale) would work here, however I understand.
I will see if I can get a windows server for you near your location with less latency

**Comment by xplshn** [comment]
That'd be handy, I haven't even tried to compile `bigdl` in Windows, it never crossed my mind to do so. If you can give me a helping hand I have no problem adding official support for windows or doing so in another branch that'll be kept updated.

**Comment by xplshn** [comment]
@Azathothas Can you help me out with Windows support? I've made changes to the `dev` branch, how do env vars and directories work in Windows? I don't think WINE is the correct way to test this. Send me a DM in Telegram if you have the time

**Comment by Azathothas** [comment]
Put this issue on a hold for now.
I will eventually get you a windows server & an android running on a pie, then you can test.
No guarantees when that's gonna happen though.

**Comment by xplshn** [comment]
Sure

**Comment by Azathothas** [comment]
I have provisioned a Windows machine, (check your dm on TG)
I will also setup android in a few days

**Comment by xplshn** [comment]
The `dev` branch supports Android. The BIGDL_CACHE variable should be set to the value of $TMPDIR tho. I will investigate what needs to be changed in order for `bigdl` to work and compile in Windows.

**Comment by xplshn** [comment]
This issue will be marked as "Closed as not planed" in a week

**Comment by xplshn** [comment]
When you have the time to go about this, you can re-open the issue if you'd like.
